[project]
name = "wave"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "imageio>=2.36.0",
    "numpy>=2.1.3",
    "py5[extras]>=0.10.3a1",
]
